apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.persistence.storageClassType }} 
  volumeMode: Filesystem
