apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
{{ if .Values.Openshift.enabled }} 
    name: postgresql
{{ else  }}
    app: postgresql
{{ end }}    
  sessionAffinity: None
  type: ClusterIP
