apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: sonarqube-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
