apiVersion: v1
data:
  init-user-db.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRESQL_USER" --dbname "$POSTGRESQL_DATABASE" <<-EOSQL

    DROP TABLE IF EXISTS "ListEntry";
    DROP SEQUENCE IF EXISTS "ListEntry_ID_seq";

    CREATE SEQUENCE "ListEntry_ID_seq";

    CREATE TABLE "public"."ListEntry" (
        "ID" integer DEFAULT nextval('"ListEntry_ID_seq"') NOT NULL,
        "Title" text NOT NULL,
        "Description" text NOT NULL,
        "Deadline" timestamp NOT NULL,
        CONSTRAINT "ListEntry_pkey" PRIMARY KEY ("ID")
    ) WITH (oids = false);
    EOSQL
kind: ConfigMap
metadata:
  name: backendinit
  namespace: fnyerges-dev
