kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
  name: webapp
  namespace: fnyerges-dev
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
              openshift.io/imported-from: fnyerges/webapp:latest
      from:
        kind: DockerImage
        name: fnyerges/webapp:latest
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
