apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: fnyerges-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
  volumeMode: Filesystem
