apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp
  name: testapp
  namespace: todoapp
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: testapp
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testapp
        deploymentconfig: testapp
    spec:
      containers:
      - env:
        - name: CUSTOMURL
          valueFrom:
            configMapKeyRef:
              key: CUSTOMURL
              name: testappsettings
        image: webapp:latest
        imagePullPolicy: IfNotPresent
        name: testapp
        ports:
        - containerPort: 5100
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 500Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/crt
          name: tlssecretvolume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tlssecretvolume
        secret:
          defaultMode: 420
          secretName: testappservice
