apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: todoapp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeMode: Filesystem
